# Generated by Django 4.2.10 on 2024-02-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='uploads/customer/')),
                ('address', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
    ]
